<!doctype html><html lang=zh-cn><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Git merge报错：error refusing to merge unrelated histories | ongoing's blog</title><link rel=stylesheet href=/css/style.css><link rel=stylesheet href=/css/fonts.css></head><body><nav><ul class=menu><li><a href=/>首页</a></li><li><a href=/categories/>分类</a></li><li><a href=/about/>关于</a></li></ul><hr></nav><div class=article-meta><h1><span class=title>Git merge报错：error refusing to merge unrelated histories</span></h1><h2 class=date>2025/05/16</h2></div><main><h3 id=一背景>一、背景</h3><ol><li>电脑本地的一个仓库莫名其妙的没有远程仓库信息了(执行 <code>git remote -v</code>什么输出都没有)，不知道是不是我误操作</li><li>只能重新 set-url 下远程的仓库名称</li><li>set完毕之后，我看本地 git 历史中是没有 origin 的head显示的，只有本地的。</li><li>执行<code>git pull</code>把远程仓库的信息拉取下来，这个时候遇到标题中的报错: <code>error refusing to merge unrelated histories</code></li></ol><h3 id=二修复>二、修复</h3><ol><li><p>在本地仓库中执行</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-bash data-lang=bash><span style=display:flex><span>git pull origin 你的远程仓库名称 --allow-unrelated-histories
</span></span></code></pre></div><p>这个命令执行完毕之后，git log 中正常出现了 origin 的标识。</p></li><li><p>接下来进行正常的 git 操作。</p></li></ol><h3 id=三为什么会出现这样的报错>三、为什么会出现这样的报错?</h3><ol><li>我的本地分支是一个测试分支，保留着未修改的原始 commit 信息</li><li>远程的分支 commit 信息因为一些信息的变更，全部重新生成了 commit hash id ，虽然 commit message
还是原来的信息，但是 commit id 已经变更</li><li>所以这两个分支虽然表面看起来一样，那些 git 提交历史一样，但是它们并没有共同的祖先，所以报错不相关。</li><li>很容易的验证：查看第一个提交，内容虽然一样，但是 commit id 是不同的。</li></ol></main><script>document.addEventListener("DOMContentLoaded",function(){const e=new PhotoSwipeLightbox({gallery:".pswp-gallery",children:"a",pswpModule:PhotoSwipe});e.init()})</script>